FROM node:18-alpine
RUN apk update && apk upgrade --no-cache && apk add --update --no-cache make gcc g++ git curl openssl openssh

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Build backend code
COPY . /usr/src/app
RUN npm ci && \
     npm cache clean --force && \
     npm run build 

# Build frontend code using SvelteKit
RUN npm install -g pnpm
WORKDIR /usr/src/app/frontend
RUN pnpm install && \
    pnpm build && \
    mv ./build ../dist-frontend

# This quick hack invalidates the cache.
ADD https://www.google.com /time.now

ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000

CMD ["node" , "./built/server.js"]
